//Economy stuff

#define GALACTIC_CURRENCY_SINGULAR "Thaler"
#define GALACTIC_CURRENCY "[GALACTIC_CURRENCY_SINGULAR]s"
#define CASH_AMOUNT_TEXT(amount) "[amount > 1? GALACTIC_CURRENCY : GALACTIC_CURRENCY_SINGULAR]"
