/atom/movable/proc/is_contraband()
	return

var/global/potential_contraband = list(
	CONTRABAND_CANNABIS,
	CONTRABAND_ALCOHOL,
	CONTRABAND_ECSTASY,
	CONTRABAND_PSILOCYBIN,
	CONTRABAND_CRACK,
	CONTRABAND_COCAINE,
	CONTRABAND_HEROIN,
	CONTRABAND_METH,
	CONTRABAND_NICOTINE,
	CONTRABAND_STIMM,
	CONTRABAND_CYANIDE,
	CONTRABAND_CHLORAL
	)

var/global/contraband_classifications = list(
	ILLEGAL,
	PROFESSIONAL_ONLY,
	PERMIT_SELLING,
	PERMIT_POSSESSION,
	LEGAL
	)